name: examens_final_A57
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: "$GITHUB_USERNAME"
          GITHUB_EMAIL: "$GITHUB_EMAIL"
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          
          export MLFLOW_TRACKING_USERNAME=mkbensmaia
          export MLFLOW_TRACKING_PASSWORD=faec1e24063e41eaf6fa47c676d5549bf3df6e36
          
          #python Pointure_GaussianNB.ipynb
          jupyter nbconvert --to notebook --execute Pointure_GaussianNB.ipynb

          # Write your CML report
          echo "# Metriques:" > report.md
          cat metrics.txt >> report.md

          ls -lrt 
          
          

          git config --local user.email "$GITHUB_EMAIL"
          git config --local user.name "$GITHUB_USERNAME"
          git add mlruns metrics.txt report.md
        
          echo $(date +%Z)
          git commit --allow-empty -m "push at $(date +%d-%b-%H_%M)"
          git tag -a "v1.0" -m "tag avec temoin.txt depuis gitactions"

          git push --follow-tags


      
